# Configuration file for Luminos.     http://luminos.menteslibres.org
#
# You are viewing a YAML formatted file, read more about the format
# at http://www.yaml.org.
#
# Note: Use two space indentations instead of the \t character.
#
#

page:
  # Name of the site.
  brand: "golang.mx"

  # Some properties for <head>.
  head:
    # Title that appears on the <title> tag.
    title: "golang.mx - Comunidad de usuarios Go en México"

  # Some properties for <body>.
  body:
    # Title that appears on the <h1> tag.
    title: "golang.mx"

    # Top navigation bar.
    menu:
      - { text: "Proyectos", url: "/proyectos" }
      - { text: "Foro", url: "https://groups.google.com/forum/#!forum/golang-mx" }
      - { text: "Go+", url: "https://plus.google.com/communities/110325783890611262108" }

    # Top-right navigation helper.
    menu_pull:
      - { text: "Portada", url: "/" }
